### ISSUE TITLE
Usher quick-link no longer uses GISAID-only sequences

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#1035]
I've noticed that when I click the "view in Usher" button, the Usher tree seems to no longer use the public + GISAID tree - using only public sequences. Maybe there's been a change in Usher API?

@AngieHinrichs do you know?

**Comment by AngieHinrichs** [comment]
Thanks Cornelius, sorry I didn't anticipate that would have side-effects like this!

**Comment by corneliusroemer** [comment]
No worries! It was easy to figure out - the new link is correct, isn't it? :)

**Comment by AngieHinrichs** [comment]
Sorry but I'm going to need to tweak the file name one more time: I will make it a .pb.gz instead of .pb.  But at least this time we can coordinate in advance to reduce the time window in which CoV-Spectrum and usher.bio are out of sync.

usher.bio config is copied out from a staging area by a cron job that runs at 1am, 7am, 1pm and 7pm PST daily.  Adding 9 hours, that means 10am, 4pm, 10pm and 4am in your time zone.  If you can tell me a date, and choose either the 4pm or 10pm CET time when you can switch over CoV-Spectrum from .pb to .pb.gz, then I can update the file in the staging area in advance of the cron job, so hopefully we can update within a few minutes of each other.  Will that work for you?

**Comment by chaoran-chen** [comment]
Hi @AngieHinrichs, thanks a lot for the heads up! What about this Wednesday (13 November) 4pm CET? This would work very well for me.

**Comment by corneliusroemer** [comment]
Thanks for the heads up :) no worries if there's brief out of syncness

**Comment by AngieHinrichs** [comment]
> this Wednesday (13 November) 4pm CET

Sounds good!  I will update the staging area just before then.

**Comment by AngieHinrichs** [comment]
I updated the staging area and will monitor to make sure it goes out as expected.

**Comment by AngieHinrichs** [comment]
.pb.gz now.  🙂

**Comment by chaoran-chen** [comment]
okay, perfect! Just started deploying the updated version: https://github.com/GenSpectrum/cov-spectrum-website/commit/4950b0e9e647b0d81e9ae10785723e3b74cb2d4f

Thanks again!!
