### ISSUE TITLE
Align date axes

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#106]
At least whenever a fixed date range is provided (i.e., not "All times" is selected in the date filter in the header), ~all the plots that have a temporal x-axis~ the "sequences over time" and "estimated cases" plots should be aligned.

A few discussion points:

- When 2020 is selected, should the plots start at 01.01, or at the date when the first sars-cov-2 sample was sequenced (in that country), or when the variant was first found (in that country)?
- When 2021 is selected, should the plot go until 31.12.2021 or until today?
- It would be great to have the plots go until today rather than the last (non-zero) data point. However, the default selection (the blue bar) in the current time plot would then always be zero since we won't have any sequences in the ongoing week.

**Comment by spacephoton** [comment]
Maybe an option is to have the selection go by default to the latest entry with enough data? for example if no sequecees for current week , then it highlights the previous by default? But then it might be missleading for the user when seing the metrics since they wont match

**Comment by ningxie1991** [comment]
> At least whenever a fixed date range is provided (i.e., not "All times" is selected in the date filter in the header), all the plots that have a temporal x-axis should be aligned.
> 
> A few discussion points:
> 
> * When 2020 is selected, should the plots start at 01.01, or at the date when the first sars-cov-2 sample was sequenced (in that country), or when the variant was first found (in that country)?
> * When 2021 is selected, should the plot go until 31.12.2021 or until today?
> * It would be great to have the plots go until today rather than the last (non-zero) data point. However, the default selection (the blue bar) in the current time plot would then always be zero since we won't have any sequences in the ongoing week.

- Personally, I think it's better to start the plot at 01.01 instead of the first date when the sample was sequenced or variant was found in the country. The user can see for themselves when the sequencing or variant first started on the plot if we start the plot from 01.01. But if we do it the other way, I feel that it could be confusing to user as whether there is data missing or the date range selection is not working properly or the plot is not showing all the data for that year. 

- I think for the current year, we should go until today instead of the end of the year.

- For the third point, if the data is 0 for the ongoing week, there won't be a blue bar is it (since the number is 0)? Maybe we just need to make sure the association between the big 0 and the week number (current week) is stronger so it's more obvious to users that the 0 is for current week only? Or we can add another number that shows the total samples over the selected date range on the plot. Other than that, I don't think it would be a problem if default selection is showing 0 for ongoing week if we don't have any sequences for that week.
