### ISSUE TITLE
Estimated cases plot: respect the date filter

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#126]
The sequencing intensity dataset and plot currently are currently not filtered by the date filter. But the dataset is now passed into the estimated case numbers plot which at the same time uses the variantSampleSet which follows the data filter. This mismatch leads to wrong results (zeros) when a date range with a closed end (e.g., 2020) is selected.

Example: 

![image](https://user-images.githubusercontent.com/18666552/117684174-079f2800-b1b5-11eb-8160-84aa82eb6b16.png)

I'm not sure what the best way to resolve it would be...

**Comment by ningxie1991** [comment]
Should we add the date filter to the `SequencingIntensityEntrySetSelectorSchema` then?

**Comment by ningxie1991** [comment]
Actually the problem lies in the trimming of data. For the date rage 2021, we have very clear divide where `variantCount` = 0 before the start date, and then the number is never 0 again until 08.08.21. This data makes the `trimStartBy` function work as expected. However, for the date range 2020, only 30 dates have `variantCount` > 0 and they are not next to each other, so this data breaks the `trimStartBy` function, and the filtered data still contains those with `variantCount` = 0

Y2021:
![image](https://user-images.githubusercontent.com/3387698/129220195-75803edf-042c-4533-aa35-11f1de3cfaa6.png)

Y2020:
![image](https://user-images.githubusercontent.com/3387698/129221255-87bb72a4-8e83-435c-9dab-297f5658197c.png)
