### ISSUE TITLE
Is AY.1 (B.1.617.2.1) counted as part of B.1.617* and/or B.1.617.2?

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#168]
Can you confirm that AY.1 (B.1.617.2.1) is properly accounted for under the headings B.1.617* and B.1.617.2? 

It's Delta with K417N and has been discussed at length in the most recent PHE report. It's definitely a variant to watch.

It should replace B.1.617.3 of which there have been no observations at all in Switzerland.

![image](https://user-images.githubusercontent.com/25161793/121790258-d368be00-cbdd-11eb-85c2-5c71ae02cbc3.png)

**Comment by chaoran-chen** [comment]
Thanks again for pointing out the missing alias-awareness! The issue was resolved in #169.

B.1.617* and B.1.617.2* now include AY.1.

(I will maybe replace B.1.617.3 with AY.1 later.)

**Comment by corneliusroemer** [comment]
Wow that's great, I'll have a look in a second.

Why do you want to replace B.1.617.3 with AY.1? That's not correct, is there a typo?

**Comment by chaoran-chen** [comment]
I meant in the list of fixed known variants because, as you pointed out, it is not relevant for CH (and also barely present in other countries: https://cov-spectrum.ethz.ch/explore/United%20Kingdom/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.3%22%2C%22mutations%22%3A[]%7D%2C%22matchPercentage%22%3A1%7D/international-comparison).

(And we can also lose B.1.617, it has currently only two sequences in the world.)

**Comment by corneliusroemer** [comment]
Ah right, yes, replacing in that sense would be good!
