### ISSUE TITLE
Compare Variants

### ISSUE THREAD

**Issue by spacephoton** [GenSpectrum/cov-spectrum-website#175]
How to compare variants?

- Somehow reuse the existing?
- Analyze all aspects? Geo, timeplot, metadata, etc => Big overall picture
- What mutations make two lineages different?
- Identify properties that make mutation important
@chaoran-chen anything else to add?

**Comment by corneliusroemer** [comment]
- Estimate relative transmission advantages using multinomial fits

**Comment by chaoran-chen** [comment]
I see three important aspects:

**(I) How should the user select multiple variants to compare? How does the user experience/journey look like?**

I don't really have a good suggestion, yet. A simple way is probably to introduce a second tab on the explore page (as we had before).

**(II) Should the user be able to select overlapping variants? (I.e., allow variants defined by mutations, and e.g., comparing B.1\* with B.1.1)?**

Yes! We definitely need to support this as it is a core feature of cov-spectrum (also conceptually) to support searches by mutations. For most of the plots, it shouldn't be a problem. "Estimate relative transmission advantages using multinomial fits" as @corneliusroemer suggests, might be difficult and we might not show it for overlapping variants until we find a mathematically sound solution.

**(III) Which plots do we show and how?**

I suggest that we keep the focus page structurally the same as now - as far as possible. It would be great if we can provide the user with the same type of plots and structure.

- Sequences over time: For the comparison, we might want to use a line plot instead.
- Estimated cases: Omit the confidence intervals, otherwise, just add more lines.
- Demographics: Just add more bars (in different colors)?
- Hospitalization probabilities: That's going to be hard to implement, I guess.. Currently, the plot already compares two variants and it looks okay, but more than two might be difficult. We might want to show the probabilities of different variants next to each other.
-  Estimation of the current advantage: Will be replaced by a more suitable model.
- Geography: Extending the table should be easy.
- Wastewater prevalence: Nope! Probably not going to show it on the comparison site.
- International comparison: Nope!
- Publication and pre-Prints: don't show as well
- The mutations: We should show both the shared and not shared mutations, maybe using a table (rows are the mutations, columns are the variants, write the percentages in the cells?)

**Comment by corneliusroemer** [comment]
Can you give examples for what sort of variants you'd like to compare and what the reason for this is?

Is it to do cleaner comparisons, that are more stable between countries, that is, you avoid the fact that if you consider one variant against the rest, the rest may differ a lot between countries.

**Comment by chaoran-chen** [comment]
One current use case I have: compare the different AY variants.
