### ISSUE TITLE
Auto completion for the search

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#197]
This needs improvement: https://github.com/cevo-public/cov-spectrum-website/pull/196/files#diff-9cffc86fd52ae1003f001fe3514627a2ae02a02d7e80c736fab0bad78714299bR52

**Comment by chaoran-chen** [comment]
The `/resource/reference-genome` endpoint ([documentation](https://github.com/cevo-public/cov-spectrum-docs/blob/develop/API.md#reference-genome)) should be quite useful.

**Comment by chaoran-chen** [comment]
@corneliusroemer, how would your dream auto-completion/recommendation for the search field look like? Imagine that it is possible to search for pango lineages, gisaid clades, nextstrain clades, aa and nuc mutations.

**Comment by corneliusroemer** [comment]
Very good question, I've been thinking about this.

So most important is:

For pango lineages: when I type, it automatically suggests children and wildcard, wildcard first, most common children after. So for example:
type "AY", get:
- AY*
- AY.4*
- AY.4
- AY.34*
- AY.34
- ...

For AA mutations: after the gene is entered, get auto suggestions for most common mutations (but not those with >90% since they are not informative) (dream: filtered by pango lineage if pango already selected). 

Type "S:" get:
- S:222V
- S:677H
- ...

For nuc mutations: same as for AA:

Type "nuc:" get:
- nuc:23094T
- nuc:8034A
- ...

That's pretty much it, is that clear? Oh yes, and ideally one gets counts for each selection, like outbreak.info does. So behind S:222V it would list the number of times that it appears within the given query.

So basically you'd send off something to the server everytime the user selects something and then provides auto suggestions based on the results (until result received, use the last received results).

So when user selects "Germany", fire off a query to find the most frequent: a) pango lineages in Germany (including .* queries), b) most common mutations in Germany (that are not >90%)

Same thing when first pango is entered, for example "Germany">"AY.4*" fire off to server asking which mutations are most common in Germany within that range.

Those things should mostly be pre-computed/cached. It's easy to do that calculation for every country once a day, plus for every mutation (global). Whether it makes sense to precompute country>pango I'm not sure, but the first two should be worth it to be very responsive to the user.
