### ISSUE TITLE
Alias wildcards don't work anymore in queries: B.1.617.2* only yields B.1.617.2

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#234]
Alias wildcards don't work anymore in queries: B.1.617.2* only yields B.1.617.2 instead of B.1.617.2 plus all AY.*: https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22b.1.617.2*%22%2C%22mutations%22%3A[]%7D%2C%22matchPercentage%22%3A1%7D

Wildcards generally still work, except in the case of aliases: https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22ay*%22%2C%22mutations%22%3A[]%7D%2C%22matchPercentage%22%3A1%7D

**Comment by chaoran-chen** [comment]
Hmm.. it seems to be case sensitive. If you put in "B.1.617.2*" instead of "b.1.617.2*", it works:

https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A%5B%5D%7D%2C%22matchPercentage%22%3A1%7D

**Task of this issue: Make the queries case insensitive!**

**Comment by chaoran-chen** [comment]
This is a duplicate of #199, so I'll close this one.
