### ISSUE TITLE
Pango query often loads forever

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#237]
I've noticed that the pango query (top panel) often loads forever. Looks like a bug to me.

It's not the case for all queries, just for some, like this one for example: https://cov-spectrum.ethz.ch/explore/Singapore/AllSamples/Past3M/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22s%3A1264L%22]%7D%2C%22matchPercentage%22%3A1%7D

![image](https://user-images.githubusercontent.com/25161793/134707602-69881448-4308-4468-8d01-d946fa1a6a21.png)

**Comment by chaoran-chen** [comment]
![image](https://user-images.githubusercontent.com/18666552/134710040-2deb87df-8739-46eb-89ae-b8697fa50b5f.png)

Argh.. What's going on there?

**Comment by ningxie1991** [comment]
@corneliusroemer @chaoran-chen 
The steps to reproduce this bug are:
1. Pick a variant and load the focus page 
2. Change the date from date filter
3. Pick a different variant
4. The new variant pangolin lineage API calls gets called repeatedly

Investigation:

Line of code that's of concern:

https://github.com/cevo-public/cov-spectrum-website/blob/6177a341e456427e0a699663863f1d9df5561828/src/components/VariantLineages.tsx#L59


Potential cause:

Whenever VariantLineages gets rendered the dateFrom and dateTo is considered changed when date filter is changed? 

Potential fix:

I removed the `dateFrom` and `dateTo` variables form the dependency list, the problem is gone on my local build.

**Comment by chaoran-chen** [comment]
If we remove `dateFrom` and `dateTo` from the dependency list, wouldn't react-query consider queries with different date range as equivalent, thus, potentially return the wrong results?

We could use `UnifiedDay` objects for the two parameters which are guaranteed to be reference equal (https://github.com/cevo-public/cov-spectrum-website/blob/develop/docs/date-cache.md).
