### ISSUE TITLE
Country missing: Martinique

### ISSUE THREAD

**Issue by c19850727** [GenSpectrum/cov-spectrum-website#277]
Hi there,

Martinique is submitting sequences onto GISAID, but it seems it's missing in covSPECTRUM though.

![image](https://user-images.githubusercontent.com/86835836/137952758-2a9e362a-aa66-4a77-a33a-2771987dfaa5.png)

Thanks

- Hitoshi

**Comment by corneliusroemer** [comment]
Martinique may be classified as France? Not sure... But yes, it would help if these Islands were tracked as countries of their own rather than as part of France. Same with Aruba and Netherlands. Aruba should be country of its own in South America, not Netherlands.
@chaoran-chen what do you think? Could this be done?

**Comment by chaoran-chen** [comment]
Hi. With #264, the overseas areas are classified as separate countries. You can try it out here: https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/Martinique/AllSamples/AllTimes/variants?pangoLineage=B.1.617.2*
