### ISSUE TITLE
[Performance] Are there plans to improve performance? Website generally feels sluggish.

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#279]
I love covSPECTRUM. But I must say it's a bit of a pain how slow it is. It's usual for queries to take 10-20s to load, that really slows down my workflow with it.

Have you profiled what excactly is slow and how you could speed it up?

@chaoran-chen I remember you saying you work on ETH servers. Would it maybe make sense to use professional cloud infrastructure instead, if that's faster?

**Comment by chaoran-chen** [comment]
The LAPIS server software is more efficient, so I would like to wait until #264 is merged and see if it is getting better.

**Comment by corneliusroemer** [comment]
Is it the one available here? https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/United%20States/AllSamples/Past3M/variants?aaMutations=Orf1a%3A2529V%2CS%3A222V&pangoLineage=AY.4*

This request took nearly 40 seconds: https://cov-spectrum.ethz.ch/gisaid/api/v1/sample/aggregated?fields=date,region,country,division,age,sex,hospitalized,died,fullyVaccinated&host=Human&country=USA

That's very much too long :/

Once cached, things work better. So maybe you could speculatively calculate queries that are likely to be executed? You could populate from most common past queries, and precalculate with any data update. And if I query something in country A, you could cache already for all countries, or at least common countries.

![image](https://user-images.githubusercontent.com/25161793/138117277-676b0eb8-0585-4294-8aa7-83a1f3ea514b.png)

**Comment by chaoran-chen** [comment]
For now, it uses a simple LRU cache. Whenever new data arrives, the old cache will be truncated, but there is a pre-computation service that computes everything that was previously in the cache.

It is currently very slow because (1) you are the only user, so you can't use anything cached for others, and (2) it is in active development and the cache is being reset all the time. In the future, I imagine that the basic, country-wide queries will always be cached, which also reduces the overall load for the server which should make other, non-cached requests faster.

**Comment by chaoran-chen** [comment]
Closing as this issue does not contain any clear todo items. See: #298
