### ISSUE TITLE
[Performance] Something's not working correctly with cache: even the main page takes 35s to load

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#295]
Something odd must be going on with the cache. Even a few requests on the main page take more than 5s, one even 35s!

https://cov-spectrum.ethz.ch/api/v2/resource/case?fields=region%2Ccountry%2Cdivision%2Cdate
https://cov-spectrum.ethz.ch/gisaid/api/v1/sample/aggregated?fields=date%2Cregion%2Ccountry%2Cdivision%2Cage%2Csex%2Chospitalized%2Cdied%2CfullyVaccinated&host=Human

Shouldn't the editor choice always be the same for every country and thus be cached and load really fast?

See screenshot of dev tools:
![image](https://user-images.githubusercontent.com/25161793/138771748-6e3c702c-f6f6-4317-a837-a80fd9cccb7b.png)

**Comment by chaoran-chen** [comment]
There are two problems:

1. Currently, only LAPIS uses a cache but CoV-Spectrum's own API's `/resource/case` endpoint does not.
2. The compression takes time. [Your second URL](https://cov-spectrum.ethz.ch/api/v2/resource/case?fields=region%2Ccountry%2Cdivision%2Cdate) returns >200MB data (if uncompressed) and compressing them takes a few seconds. The current implementation is not efficient. I posted a question on Stack Overflow [1]. ~If you have experience with HTTP-compression/Nginx/Spring Boot, or know someone who does, please advise!~ (It's apparently easy to improve it.)

[1] https://stackoverflow.com/questions/69723449/http-compression-with-spring-boot-and-nginx

I'll work on them when I have time.

**Comment by corneliusroemer** [comment]
I see, sounds good!

Do you really need to block rendering while waiting for some of these requests? And why don't you just provide the aggregated output? There seems to be a lot of info that cov-spectrum doesn't actually use.

**Comment by chaoran-chen** [comment]
> Do you really need to block rendering while waiting for some of these requests?

It's possible to improve but it will take some effort and increase the code complexity.

> And why don't you just provide the aggregated output? There seems to be a lot of info that cov-spectrum doesn't actually use.

Currently, the web app makes a big request rather than many small ones. Your second URL fetches data that are stratified by date, age, division, hospitalization, and death status. It's big but it allows us to create the Sequences over time, Age demographics, Hospitalization probabilities, Death probabilities, and Geographic distribution plots. The alternative would require five parallel requests. - The server prefers fewer requests.

A few improvements can be made: e.g., there is no need to fetch the country if we are filtering a country. And the region field is also not needed.

**Comment by chaoran-chen** [comment]
Closing as this issue does not contain any clear todo items. See: https://github.com/cevo-public/cov-spectrum-website/issues/298
