### ISSUE TITLE
Question: Is it possible to search for any mutation BUT deletion?

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#346]
Say I want all aa muts S:484K/Q/... but NOT S:484-

Question from @zach-hensel

**Comment by chaoran-chen** [comment]
No, not yet. But since this is already the third request for complex queries, I created an issue to collect them: #347.

**Comment by zach-hensel** [comment]
FYI the temporary solution to my question was to go to cov-glue and look at all mutations and then go back to cov-spectrum to look in depth. The problem is just that rare mutations are overwhelmed by less rare bad sequences with apparent deletions.

A cool UI would be if the drop down list was dynamically populated by the most frequent variations finishing the query so in this case I would've typed ORF1a:2830 and seen a dropdown list "-, R, etc" and clicked on "R". Cool but probably not trivial.
