### ISSUE TITLE
Website structure

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#5]
Let's collect some ideas for the overall structure of the website.

I see two central workflows for the platform:

- The user wants to know what's going on in a country. Then, she might want to start the journey at a dashboard that shows the table with uprising variants (our current "Find new variants" tab) but also other statistics such as the number of sequenced samples through time and their geographic distribution. A plot similar to https://covariants.org/per-country would be super cool but it might be difficult to build since variants - we define them simply as a set of mutations - are not distinct. I.e., a sample is assigned to a large number of variants.
- The user wants to know what's going on with a variant: both for a particular country and globally (maybe with an emphasis on the neighboring countries).

When seeing an interesting variant, the user could want to know "everything" about it, especially where it was found, how it spread through time, etc.

What would be a good structure to support these flows?

**Comment by chaoran-chen** [comment]
Just to put something in the room, here is a first draft:

### Landing page

![Landing](https://user-images.githubusercontent.com/18666552/108611471-0d1f7a00-73df-11eb-96e6-8a5df3a2a479.png)


### Country list

![Country List](https://user-images.githubusercontent.com/18666552/108611444-d6496400-73de-11eb-9717-dd4f8e2a57ec.png)


### Selected country: overview

![Country](https://user-images.githubusercontent.com/18666552/108570670-c5c9b880-730e-11eb-896e-392cdf089c2f.png)


### Variant list

![Variant List](https://user-images.githubusercontent.com/18666552/108611450-e19c8f80-73de-11eb-8cfb-bdefd2bfcb5e.png)



### Selected variant

![Variant](https://user-images.githubusercontent.com/18666552/109285156-0189e400-7821-11eb-8b99-29751e7606ef.png)


In the top-left picker, the user can either select a country, or a region (e.g., Europe), or "global".

**Comment by tehwalris** [comment]
The two workflows that @chaoran-chen presented are something that I summarize as "explore" and "focus". I tried to make this separtion of concepts the core of my design. The user always starts out in "explore", jumps back and forth into "focus". Sometimes (but not usually) the user goes deeper into the "focus" workflow.

The main screen of my UI proposal (below) shows an "explore" panel on the left and a "focus" panel on the right. This way the user can quickly select a variant and see the most important details without interrupting their exploration. I expect that users will spend most of their time on this screen. The "explore" panel (left) gives an overview of the situation in a country and lets the user select variants in all the ways that we currently support. I also added little sparkline plots and bits of information to variants, so that the user has some way to decide which ones to click.

![cov-spectrum-explore-focus](https://user-images.githubusercontent.com/1489115/109296811-3dc54080-7831-11eb-96c1-5c281b8e6f05.png)

So that the user can quickly see a variety of important information, the "focus" panel (above, on the right) shows different aspects of the data, but only as non-detailed summaries (eg. a single simple plot). If something (eg. the demograhics plot) seems interesting, the user look deeper into that. This takes the user to a full screen exploration (below) of that specific aspect of the variant, which contains more plots and controls. This is the "deep" part of the "focus" workflow. This completely pulls the user out of the "explore" experience - that is done to simplify navigation and not overload the the user with information and controls.

![cov-spectrum-focus-deep](https://user-images.githubusercontent.com/1489115/109296820-40279a80-7831-11eb-8e73-828a6bab68f2.png)

In the very top bar of the UI I placed some global filters. In our current design we have a seprate country selection per screen, which I personally find very disorienting. In this design the country is switched globally, which adjusts all the plots, searches, etc. In addition I added a filter to show only randomly samples sequences, which we will hopefully support in the future.
