### ISSUE TITLE
Compare variants tooltip broken when CI is shown

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#527]
If I turn off the CI:

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/18666552/179426445-964e4624-5cba-4136-806d-12bfc21588a9.png">

If I turn on the CI:

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/18666552/179426462-18cbe617-511c-4798-9994-ae7ac8564670.png">

https://cov-spectrum.org/explore/Germany/AllSamples/Past6M/variants?pangoLineage=BA*&pangoLineage1=BA.5*&pangoLineage2=BA.4*&pangoLineage3=BA.1*&pangoLineage4=BA.1.1.15&analysisMode=CompareEquals&

@anastasia-escher, do you know what is causing this?

**Comment by anastasia-escher** [comment]
Hi @chaoran-chen! The issue was that the Tooltip wanted to show info on every object on the plot, including areas which had a transparent stroke and could not be seen on the tooltip and only took a lot of space. 
It is fixed here:
https://cov-spectrum-develop-94o4boce6-cov-spectrum.vercel.app/explore/Switzerland/AllSamples/Past6M

Does it look ok?

**Comment by chaoran-chen** [comment]
Yes, that looks good 👍
