### ISSUE TITLE
ENH: Make "now" not "now" but "now - 1 week" in past month etc. periods

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#611]
The covSpectrum date default selection currently goes till today which has the consequence of showing _very_ noisy periods that should probably better be hidden.

Nothing would be lost by showing data only till "today - 1 week", this would also fix the fact that we often see 0-100% in the number on the right (h/t @emmahodcroft)
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/25161793/193568238-9d8174c9-2bc5-441a-8b42-3a182d2721c2.png">

**Comment by emmahodcroft** [comment]
This was brought up because I always get confused when I have a graph (or something like a graph) but then it says 0% on the right - makes me double-take because I wonder if I've misunderstood if there's no data or some data.

I'd also suggest maybe adding in small font below the "0.0% Proportion 0.0-100.0% confidence int" the total number of sequences in the graph - just lets one do a very quick sanity check to estimate how much data is behind the chart! (One can click on 'absolute' to see this but at a glance it can be hard to see.)

In particular for me it can be tricksy that the confidence interval changes over time, even though there's no data - that's unintuitive for me! 🙃 
![image](https://user-images.githubusercontent.com/14290674/193568763-7bfc4954-8648-4a8b-a1e9-2dc9ca5b2a83.png)

**Comment by chaoran-chen** [comment]
Thanks for the suggestion! I implemented it. I also changed the preview plots on the left side to ignore one week of data.

**Comment by corneliusroemer** [comment]
Thank you so much :)

**Comment by corneliusroemer** [comment]
Excellent, much better! We should think about whether making it 10 days rather than 7 could be better. The most recent data is so unreliable and sparse. But this is easy to change, I can play around with a PR myself ;) 

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/25161793/193998352-ca549b86-adde-40a8-b45d-071bd5f1574c.png">

**Comment by emmahodcroft** [comment]
This is great, thanks @chaoran-chen !
