### ISSUE TITLE
General breakage?

### ISSUE THREAD

**Issue by theosanderson** [GenSpectrum/cov-spectrum-website#694]
Fyi, any sort of search from https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past6M is getting me `assertion_error.js:392 Uncaught ReferenceError: process is not defined` in console atm and not working

**Comment by chaoran-chen** [comment]
Thank you very much, @theosanderson!! I wasn't aware of the error at all. It only occurred on pages of countries that have a name containing a space. In manual tests, I usually only visit Switzerland and World, so the issue was never raised.

Whenever you see something not working, please create an issue as soon as possible! Even though it might be obvious, I might not have noticed :)
