### ISSUE TITLE
Highlighted bar in demographics plot

### ISSUE THREAD

**Issue by tehwalris** [GenSpectrum/cov-spectrum-website#75]
Currently the demographics plot highlights the last bar ("80+") when the user is not hovering a specific bar:

![demographics-last-column-highlight](https://user-images.githubusercontent.com/1489115/113283157-2c67cc00-92e8-11eb-8e4f-9f394f1fc5fc.png)

This made a lot of sense for the time distribution plot, but not really for demographics. Maybe we should not highlight any bar by default? Could be show some more useful stats instead, like proportion of samples with age info?

**Comment by spacephoton** [comment]
Maybe simple change for now is to highlight the one with the max cases?

**Comment by chaoran-chen** [comment]
I actually like the idea of showing the proportion of samples with age info because it is quite important information that is not being shown at all yet. And, it makes sense to see the information at the very beginning because the plot is only useful if we have a large number of samples with age information.

**Comment by chaoran-chen** [comment]
@TKGZ changed it so that the age group with the highest number is pre-selected. That's good enough for now.
