### ISSUE TITLE
Replace Zod

### ISSUE THREAD

**Issue by tehwalris** [GenSpectrum/cov-spectrum-website#79]
It turns out that Zod is actually [very slow](https://github.com/moltar/typescript-runtime-type-benchmarks). We should switch to a different validation library. Probably something based on `ajv` which is robust and widely used (it uses codegen, so it's fundamentally faster).

After we switch we should re-enable validation for `getNewSamples` and `getInterestingVariants`, since they were disabled in #78 because Zod was too slow to use.

**Comment by spacephoton** [comment]
What was the main advantage of us using Zod in our use case?

**Comment by chaoran-chen** [comment]
The wastewater data will also not be parsed by Zod anymore because it is too slow.

**Comment by chaoran-chen** [comment]
We now disable zod for multiple requests because of this issue. Thus, raising the priority and moving it back to the Todo list.

**Comment by ningxie1991** [comment]
@TKGZ @chaoran-chen 

I found this [blog](https://blog.logrocket.com/dynamic-type-validation-in-typescript/#:~:text=Generation%20of%20validators) that introduces [typescript-json-validator ](https://github.com/ForbesLindesay/typescript-json-validator). Basically it's using ajv and can "automatically generate a validator using JSON Schema and AJV for any TypeScript type". Also, I found [quicktype](https://github.com/quicktype/quicktype) kind of promising. 

In addition, according to this github [issue](https://github.com/colinhacks/zod/issues/205), we can try upgrading zod version to latest one or try [myzod](zalando.ch/crocs-crocband-pantolette-flach-cr411f004-j12.html).

**Comment by ningxie1991** [comment]
Update on upgrading Zod version to the latest 3.7.1 in local environment:

| Zod version | Test Plot | Performance (milliseconds) |
| ------------- |:-------------:| -----:|
| 3.0.0-alpha.4 (current)  | B.1.1.7 alpha / WasteWaterResponseSchema.parse(json)  | 76012.59999999404 |
| 3.7.0  | B.1.1.7 alpha / WasteWaterResponseSchema.parse(json) | 96.7000000178814 |
| 3.7.1 (latest) | B.1.1.7 alpha / WasteWaterResponseSchema.parse(json) | 86.30000001192093 |

I tested the plots from the Editor's choice, and most of the performance time ranges from 72 ms to 85 ms for the `WasteWaterResponseSchema.parse(json)` function call in [/src/wasteWater/loading.ts](https://github.com/cevo-public/cov-spectrum-website/blob/ca257c7ed0e8f16e395adf9a4889734e729d860c/src/models/wasteWater/loading.ts#L24). Is this a good enough performance? @chaoran-chen Since the code is heavily written with Zod, replacing Zod would take a lot of time and effort. Zod is a neat tool as compared to other validator libraries. So I think we should probably keep it and upgrade to 3.7.1 if this performance is acceptable.

**Comment by ningxie1991** [comment]
> We now disable zod for multiple requests because of this issue. Thus, raising the priority and moving it back to the Todo list.

For these api requests below, I did not see too much performance difference for `InterestingVariantResultSchema.parse` and for `CaseCountEntrySchema` and `RawMultiSampleSchema`, the difference between using Zod (**v3.7.1**) and deactivating Zod is about adding 100 - 300 ms. 

https://github.com/cevo-public/cov-spectrum-website/blob/cc68c56b8ac8aeb2a0e395877f5272edc03ebfce/src/services/api.ts#L394-L396

https://github.com/cevo-public/cov-spectrum-website/blob/cc68c56b8ac8aeb2a0e395877f5272edc03ebfce/src/services/api.ts#L517-L519

https://github.com/cevo-public/cov-spectrum-website/blob/cc68c56b8ac8aeb2a0e395877f5272edc03ebfce/src/services/api.ts#L218-L220

**Comment by chaoran-chen** [comment]
Interesting! Then, I would suggest that we update and stay with zod. We can activate it for the wastewater endpoint (because it is less reliable) and can keep it for /sample2 disabled if we are not fully happy with the performance.

**Comment by ningxie1991** [comment]
> Interesting! Then, I would suggest that we update and stay with zod. We can activate it for the wastewater endpoint (because it is less reliable) and can keep it for /sample2 disabled if we are not fully happy with the performance.

OK, then I will update zod version to 3.7.1 and activate it back for wastewater. I think we can also enable it for the /sample2 requests because I don't see much difference in performance between preview and prod. But maybe I am not aware of all the use cases that could generate a big response load from those requests.

I created pull request #220 for this.
