### ISSUE TITLE
Wastewater curves do not display all available dates in selected plots

### ISSUE THREAD

**Issue by mcarrara-bioinfo** [GenSpectrum/cov-spectrum-website#896]
I have just updated the curves for the "stories" page about the wastewater in Switzerland.

The database reports that for Chur and Lausanne there are data point up to and including December 03, while for Altenrhein up to and including December 04.
However, with mouse-over at the end of the curves, we can only see data points up to December 02 for Chur and Lausanne, and up to December 03 for Altenrhein.

**Comment by JonasKellerer** [comment]
I think I have pinpointed the error, with the assumption that the data is provided for the local time of Switzerland, so CEST, or CET.  Is this correct? When we plot the data, we plot for UTC. So when the date is the 2023-12-11 00:00 in Switzerland, this should be 2023-12-10 22:00 in UTC. Because we dont show the time on the curves, we have the discrepancy, you mentioned.

Now the question is, how do we show that to the user? Do we add a description to the mouse-over, do we add the hours/minutes, or do we add a label to the graphs? (Or all together) @chaoran-chen What do you think?

**Comment by chaoran-chen** [comment]
Interesting.. Can we somehow work without timezones?

**Comment by JonasKellerer** [comment]
As discussed in person, we only use the dates without time zones.
