### ISSUE TITLE
Regression: GISAID accession list no longer opens in new tab

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#930]
There seems to be a regression for feature #444 in that the accessions are downloaded rather than opened in new file.

This is probably because there's no longer a `downloadAsFile=false` URL parameter.

Old link: https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?host=Human&region=Europe&dateFrom=2021-09-27&nucMutations=2470T%2C13195C%2CG27382C%2CA29510C%2CC26858T%2CA27383T&downloadAsFile=false&dataFormat=csv

New link: https://lapis.cov-spectrum.org/gisaid/v2/sample/details?country=Switzerland&dateFrom=2023-08-21&dateTo=2024-02-15&nextcladePangoLineage=ba.2.86*&host=Human&dataFormat=CSV-WITHOUT-HEADERS&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&fields=gisaidEpiIsl

See https://neherlab.slack.com/archives/C01M74N29RD/p1708616351775129

**Comment by fengelniederhammer** [comment]
`downloadAsFile=false` essentially [does nothing](https://github.com/GenSpectrum/LAPIS/blob/b1972cd2e244bf502d23b0c7ec42677822b921e0/lapis2/src/main/kotlin/org/genspectrum/lapis/controller/DownloadAsFileFilter.kt#L26). I will investigate why this happens...

Did you by any chance also archive what the response for the old link looked like (most importantly the headers)?

**Comment by corneliusroemer** [comment]
It's just a list of accessions, something like:

```
EPI_ISL_18861300
EPI_ISL_18832067
EPI_ISL_18763358
EPI_ISL_18782686
```

I'm not sure I have an archive, let me check!

Unfortunately I couldn't find any full requests in web archive.

**Comment by fengelniederhammer** [comment]
https://lapis.cov-spectrum.org/open/v1/sample/genbank-accession?dataFormat=csv&limit=100

has `content-disposition: inline` set. That's likely it.

**Comment by fengelniederhammer** [comment]
`content-disposition: inline` doesn't do it. If `Content-Type: text/csv` or `Content-Type: text/tab-separated-values`, then browsers refuse to display it and instead download the data.

LAPIS 1 solves this by setting [`Content-Type: text/plain`](https://github.com/GenSpectrum/LAPIS/blob/b1972cd2e244bf502d23b0c7ec42677822b921e0/server/src/main/java/ch/ethz/lapis/api/controller/v1/SampleResponseBuilder.java#L56) for [those specific endpoints](https://github.com/GenSpectrum/LAPIS/blob/b1972cd2e244bf502d23b0c7ec42677822b921e0/server/src/main/java/ch/ethz/lapis/api/controller/v1/SampleController.java#L362) that fetch accession lists.

How should we handle this in LAPIS 2? Our routing depends on the `Accept` and `Content-Type` header, so this might be difficult to overwrite. Also we don't have specific endpoints, but abuse `/details` here. 
* Would it be acceptable that we don't fix this "bug", since it's not really a bug?
* Should we try to overwrite to `Content-Type: text/plain` if `downloadAsFile` is explicitly set to `false`?

**Comment by chaoran-chen** [comment]
It is a useful feature that people use and enjoy, so we should support it.

What's about setting the `Content-Type` to `text/plain` for `dataFormat=CSV-WITHOUT-HEADERS`?

**Comment by fengelniederhammer** [comment]
> What's about setting the Content-Type to text/plain for dataFormat=CSV-WITHOUT-HEADERS?

Sounds like a possible solution. That data format is quite specific for that use case anyway. Or should we introduce yet another data format?

**Comment by fengelniederhammer** [comment]
I deployed the necessary changes, works for me in Firefox:

![grafik](https://github.com/GenSpectrum/cov-spectrum-website/assets/92720311/1bdcc566-10a8-435c-82e2-c8657c760e33)

**Comment by corneliusroemer** [comment]
Excellent, yes works for me too!

<img width="1194" alt="image" src="https://github.com/GenSpectrum/cov-spectrum-website/assets/25161793/f9c4fc60-03a7-418d-847d-a17a68b93506">
