### ISSUE TITLE
ENH:Adding a Truncations section, discussion

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/cov-spectrum-website#998]
This morning i was wondering IF and it is a big if may be consistent with an enhancement of the covspectrum tool to have a truncations section similar to the Insertions one. 
Actually we can track Insertions within that dedicated section and we can observe Deletions with the growth%by week tool but we miss to have a complete picture of truncations in a determined lineage or in a determined period.
Being outside the spike i flag it as non urgent  but that could be helpful to catch some early trend and to monitor that kind of viral evolution.
But i would like to hear about that from @corneliusroemer and @ryhisner if they agree before any implementation of it , if technically possible
Thx to all the team of Covspectrum for their hard work

**Comment by corneliusroemer** [comment]
Can you explain a bit more? What do you mean by truncations? Stop codons and frameshifts?

**Comment by FedeGueli** [comment]
Yes exactly Stop Codon and FS.
Ecample i set Spaim last momth S:F456L , it would be good to have highlighted the truncations separately on a small box as insertions.

**Comment by ryhisner** [comment]
It might be difficult to separate artifactual truncations/frameshifts from real ones. Sometimes entire uploads from labs in Spain or elsewhere are not viewable on Nextclade due to artifactual frameshifts, usually but not always around deletions or insertions.

**Comment by ryhisner** [comment]
The biggest improvement I think could be made to CovSpectrum at the moment would be a section showing the percentage of different variants that have a certain mutation. For example, let's say I want to know which lineages S:P9S is most prominent in. It would be nice to be able to see a list of variants along with the percentage of sequences within each variant have P9S. 

Outbreak dot info used to have a tool like this, but I stopped using that site because of how infrequently it was updated and the inability to do nucleotide searches + a million other things you can do on CovSpectrum. 

Below is a picture of the results of a S:P9S search from Outbreak. It's not been updated in 24 days it looks like, so this wouldn't include anything from that period. And there are no options for time periods that I can see, so this isn't nearly as useful as it could be.
<img width="738" alt="image" src="https://github.com/GenSpectrum/cov-spectrum-website/assets/33738461/e39141d7-78f5-4067-802d-e3ae685ffa25">

**Comment by FedeGueli** [comment]
Thx for the comments closing it hence
